[package]
name = "tower_runtime"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
tokio = { workspace = true }
log = { workspace = true } 
snafu = { workspace = true } 
tower_package = { workspace = true } 
