[package]
name = "tower-api"
version = { workspace = true }
edition = "2021"

[dependencies]
chrono = { workspace = true } 
config = { workspace = true } 
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
